// Mocks generated by Mockito from annotations
// in zahradnik_boda_mvp01/test/features/activity/data/activity_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zahradnik_boda_mvp01/features/activity/data/activity_hive_model.dart'
    as _i3;
import 'package:zahradnik_boda_mvp01/features/activity/data/hive_local_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HiveLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveLocalDataSource extends _i1.Mock
    implements _i2.HiveLocalDataSource {
  @override
  List<_i3.ActivityHiveModel> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i3.ActivityHiveModel>[],
            returnValueForMissingStub: <_i3.ActivityHiveModel>[],
          )
          as List<_i3.ActivityHiveModel>);

  @override
  _i3.ActivityHiveModel? getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValueForMissingStub: null,
          )
          as _i3.ActivityHiveModel?);

  @override
  _i4.Future<void> add(_i3.ActivityHiveModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#add, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i3.ActivityHiveModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
